Miel/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^menu/', include('menu.urls'), name='menu'),
    url(r'^account/', include('account.urls'), name='account'),
]

account/urls.py
from django.conf.urls import url
from django.urls import path, include

from . import views

app_name = "account"

urlpatterns = [
    url(r'^$', views.account, name='account'),
    # TODO change url syntax to ?failed
    url(r'^login//?(?P<failed>[-\w\d]+)/?$', views.login_display, name='login_fail'),
    url(r'^login/$', views.login_display, name='login'),
    url(r'^login_submit/$', views.login_submit, name='login_submit'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$', views.my_logout, name='logout'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
]

menu/urls.py
from django.conf.urls import url
from django.urls import path, include

from . import views
from . import export

app_name = "menu"

urlpatterns = [
    url(r'^$', views.analisis, name='main'),
    url(r'^proveedores/$', views.proveedores, name='proveedores'),
    url(r'^proveedores/cambiar//?(?P<pk>[-\w\d]+)/?$', views.proveedor_modifier, name='proveedores_edit'),
    url(r'^proveedores/error/$', views.proveedores_delete_error, name='proveedores_error'),
    url(r'^proveedores/suprimir//?(?P<pk>[-\w\d]+)/?$', views.del_proveedores, name='proveedores_delete'),
    url(r'^platillos/$', views.platillos, name='platillos'),
    url(r'^platillos/cambiar//?(?P<pk>[-\w\d]+)/?$', views.platillos_modifier, name='platillos_edit'),
    url(r'^platillos/suprimir/$', views.del_platillo, name='platillos_delete'),
    url(r'^bebidas/$', views.bebidas, name='bebidas'),
    url(r'^bebidas/cambiar//?(?P<pk>[-\w\d]+)/?$', views.platillos_modifier, name='bebidas_edit'),
    url(r'^ingredientes/$', views.ingredientes, name='ingredientes'),
    url(r'^ingredientes/cambiar//?(?P<pk>[-\w\d]+)/?$', views.IngredienteUpdateView.as_view(), name='ingredientes_edit'),
    url(r'^ingredientes/suprimir/$', views.del_ingredient, name='ingredientes_delete'),
    url(r'^recetas/$', views.recetas, name='recetas'),
    url(r'^recetas/cambiar//?(?P<pk>[-\w\d]+)/?$', views.recetas_modifier, name='recetas_edit'),
    url(r'^recetas/suprimir/$', views.del_receta, name='recetas_delete'),
    url(r'^exportar/$', export.export, name='export'),
]

templates/base.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png' %}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    {% block title %}Profundiza | Miel-Tech{% endblock %}
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="{% static 'assets/css/material-dashboard.css' %}" rel="stylesheet" />
  <link href="{% static 'custom/custom.css' %}" rel="stylesheet" />

  <script src="{% static 'assets/js/core/jquery.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'assets/js/plugins/jquery.form.js' %}"></script>
</head>

<body class="">
  <div class="wrapper ">
    <div class="sidebar" data-color="purple" data-background-color="white" data-image="{% static 'assets/img/sidebar-1.jpg' %}">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

        Tip 2: you can also add an image using data-image tag
    -->
      <div class="logo">
        <a href="#" class="simple-text logo-normal">
          Miel-Tech
        </a>
      </div>
      <div class="sidebar-wrapper">
         <ul class="nav">
          <li class="nav-item {% if request.resolver_match.view_name == "account:dashboard" %}active{% endif %}">
            <a class="nav-link" href="{% url 'account:dashboard' %}">
              <i class="material-icons">dashboard</i>
              <p>Tablero</p>
            </a>
          </li>
          <li class="nav-item {% if request.resolver_match.view_name == "account:account" %}active{% endif %}">
            <a class="nav-link" href="{% url 'account:account' %}">
              <i class="material-icons">person</i>
              <p>Cuenta</p>
            </a>
          </li>
          <li class="nav-item {% if request.resolver_match.app_name == "menu" %}active{% endif %}">
            <a class="nav-link" href="{% url 'menu:main' %}">
              <i class="material-icons">restaurant</i>
              <p>Ingeniera de Men&uacute;</p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="#">
              <i class="material-icons">shopping_cart</i>
              <p>Presupuesto</p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="#">
              <i class="material-icons">notifications</i>
              <p>Notificaciones</p>
            </a>
          </li>
          <!-- <li class="nav-item active-pro ">
                <a class="nav-link" href="./upgrade.html">
                    <i class="material-icons">unarchive</i>
                    <p>Upgrade to PRO</p>
                </a>
            </li> -->
        </ul>

      </div>
    </div>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            {#TODO capitalize app name #}
            <a class="navbar-brand" href="#">{{ request.resolver_match.app_name }}</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end">
            <form class="navbar-form">
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                  <i class="material-icons">search</i>
                  <div class="ripple-container"></div>
                </button>
              </div>
            </form>
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="#pablo">
                  <i class="material-icons">dashboard</i>
                  <p class="d-lg-none d-md-block">
                    Stats
                  </p>
                </a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons">notifications</i>
                  <span class="notification">5</span>
                  <p class="d-lg-none d-md-block">
                    Some Actions
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Ejemplo de notificaci&oacute;n</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="{% url 'account:account' %}">
                  <i class="material-icons">person</i>
                  <p class="d-lg-none d-md-block">
                    Account
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'account:account' %}">Cuenta</a>
                  <a class="dropdown-item" href="{% url 'account:logout' %}">Cerrar Sesi&oacute;n</a>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
      <div class="content">
        <div class="container-fluid">
            {% block content %}
            {% endblock %}
        </div>
      </div>
      <footer class="footer">
        <div class="container-fluid">
          <nav class="float-left">
            <ul>
              <li>
                <a href="#">
                  Profundiza
                </a>
              </li>
              <li>
                <a href="#">
                  About Us
                </a>
              </li>
            </ul>
          </nav>
          <div class="copyright float-right">
            &copy;
            <script>
              document.write(new Date().getFullYear())
            </script>, Profundiza.
          </div>
        </div>
      </footer>
    </div>
  </div>
  <!--   Core JS Files   -->
  <script src="{% static 'assets/js/core/popper.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'assets/js/core/bootstrap-material-design.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'assets/js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
  <!-- Chartist JS -->
  <script src="{% static 'assets/js/plugins/chartist.min.js' %}"></script>
  <!--  Notifications Plugin    -->
  <script src="{% static 'assets/js/plugins/bootstrap-notify.js' %}"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'assets/js/material-dashboard.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'custom/custom.js' %}"></script>
  <script>
    $(document).ready(function() {
      // Javascript method's body can be found in assets/js/demos.js
      md.initDashboardPageCharts();

    });
  </script>
</body>

</html>

templates/base_.html
{% load static %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css"
          href="{% static '/assets/css/bootstrap.min.css' %}"/>
    <title>{% block title %}Profundiza | Miel-Tech{% endblock %}</title>
</head>
<body>
<div class="container-fluid">
    <nav class="navbar navbar-light">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Profundiza</a>
        </div>
        <ul class="nav navbar-nav navbar-left">
          <li><a href="{% url 'account:view_apps' %}">Apps</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'account:account' %}">Account</a></li>
          <li><a href="{% url 'account:login' %}">Logout</a></li>
        </ul>
      </div>
    </nav>
    {% block navbar %}{% endblock %}
{% block content %}
{% endblock %}
    <footer id="footer">
        <div class="footer_top">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4">
                    <div class="footer_widget">
                        <h2>Never miss an exclusive discount</h2>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4">
                    <div class="footer_widget">
                        <h2>Become a Reviewer</h2>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4">
                    <div class="footer_widget">
                        <h2>Join as a Seller</h2>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer_bottom">
            <p class="copyright">Copyright &copy; 2017 <a href="">Profundiza</a></p>
            <p class="developer"><a href="">Ethics</a> | <a href="">Terms of Service</a> | <a
                    href="">Privacy Policy</a></p>
        </div>
    </footer>
</div>
</body>
</html>

templates/header.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png' %}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    {% block title %}Profundiza | Miel-Tech{% endblock %}
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="{% static 'assets/css/material-dashboard.css' %}" rel="stylesheet" />
  <link href="{% static 'custom/custom-login.css' %}" rel="stylesheet" />
</head>