Miel/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^menu/', include('menu.urls'), name='menu'),
    url(r'^account/', include('account.urls'), name='account'),
]

menu/urls.py
from django.conf.urls import url
from django.urls import path, include

from . import views
from . import export

app_name = "menu"

urlpatterns = [
    url(r'^$', views.analisis, name='main'),
    url(r'^proveedores/$', views.proveedores, name='proveedores'),
    url(r'^proveedores/cambiar//?(?P<pk>[-\w\d]+)/?$', views.proveedor_modifier, name='proveedores_edit'),
    url(r'^proveedores/error/$', views.proveedores_delete_error, name='proveedores_error'),
    url(r'^proveedores/suprimir//?(?P<pk>[-\w\d]+)/?$', views.del_proveedores, name='proveedores_delete'),
    url(r'^platillos/$', views.platillos, name='platillos'),
    url(r'^platillos/cambiar//?(?P<pk>[-\w\d]+)/?$', views.platillos_modifier, name='platillos_edit'),
    url(r'^platillos/suprimir/$', views.del_platillo, name='platillos_delete'),
    url(r'^bebidas/$', views.bebidas, name='bebidas'),
    url(r'^bebidas/cambiar//?(?P<pk>[-\w\d]+)/?$', views.platillos_modifier, name='bebidas_edit'),
    url(r'^ingredientes/$', views.ingredientes, name='ingredientes'),
    url(r'^ingredientes/cambiar//?(?P<pk>[-\w\d]+)/?$', views.IngredienteUpdateView.as_view(), name='ingredientes_edit'),
    url(r'^ingredientes/suprimir/$', views.del_ingredient, name='ingredientes_delete'),
    url(r'^recetas/$', views.recetas, name='recetas'),
    url(r'^recetas/cambiar//?(?P<pk>[-\w\d]+)/?$', views.recetas_modifier, name='recetas_edit'),
    url(r'^recetas/suprimir/$', views.del_receta, name='recetas_delete'),
    url(r'^exportar/$', export.export, name='export'),
]

menu/forms.py
from django import forms

from .models import *


class BaseModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')  # globally override the Django >=1.6 default of ':'
        super(BaseModelForm, self).__init__(*args, **kwargs)


class ProveedorForm(BaseModelForm):
    class Meta:
        model = Proveedor
        fields = ('nombre', 'telefono', 'representante', 'telefono_de_representante', 'correo_electronico')


class IngredienteForm(BaseModelForm):
    class Meta:
        model = Ingrediente
        fields = ('nombre', 'marca', 'medida', 'cantidad', 'costo',  'proveedor')


class RecetaForm(BaseModelForm):
    class Meta:
        model = Receta
        fields = ('nombre', 'medida', 'cantidad')


class RecetaCompForm(BaseModelForm):
    class Meta:
        model = RecetaComp
        fields = ('medida', 'cantidad')


class PlatilloForm(BaseModelForm):
    class Meta:
        model = Platillo
        fields = ('nombre', 'precio', 'bebida')


class PlatilloIngForm(BaseModelForm):
    class Meta:
        model = PlatilloIng
        fields = ('cantidad', 'medida')


class PlatilloRecForm(BaseModelForm):
    class Meta:
        model = PlatilloRec
        fields = ('cantidad', 'medida')

menu/views.py
from django.db.models import ProtectedError
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render, redirect, render_to_response
from django.template import RequestContext
from django.template.loader import render_to_string
from django.urls import reverse
from django.views.generic import UpdateView

from menu.forms import *
from .models import *


def recetas_modifier(request, pk):
    receta = Receta.objects.get(id=pk)
    form = RecetaForm(instance=receta)
    # Create the formset class
    RecetaCompFormset = inlineformset_factory(Receta, RecetaComp, exclude=[])
    # Create the formset
    formset = RecetaCompFormset(instance=receta, queryset=RecetaComp.objects.filter(receta=receta))

    try:
        err = request.GET['err']
    except KeyError:
        err = None

    dict = {
        "form": form
        , "formset": formset
        , "instance": receta
        , "error": err
    }

    if request.method == "POST":
        form = RecetaForm(request.POST, instance=receta)
        formset = RecetaCompFormset(request.POST, instance=receta)

        if form.is_valid() and formset.is_valid():
            client_mod = form.save()
            id = client_mod.id
            formset.save()

            # TODO redirect to receta view
            return HttpResponseRedirect(reverse('menu:recetas'))
        else:
            return HttpResponseRedirect(
                "/menu/recetas/cambiar/%(id)s/?err=warning" % {"id": pk}
            )

    return render(request, 'menu/receta_edit_form.html', dict)


def platillos_modifier(request, pk):
    platillo = Platillo.objects.get(id=pk)
    form = PlatilloForm(instance=platillo)
    # Create the formset class
    PlatilloIngFormset = inlineformset_factory(Platillo, PlatilloIng, exclude=[])
    PlatilloRecFormset = inlineformset_factory(Platillo, PlatilloRec, exclude=[])
    # Create the formset
    formset1 = PlatilloIngFormset(instance=platillo, queryset=PlatilloIng.objects.filter(platillo=platillo))
    formset2 = PlatilloRecFormset(instance=platillo, queryset=PlatilloRec.objects.filter(platillo=platillo))

    try:
        err = request.GET['err']
    except KeyError:
        err = None

    dict = {
        "form": form
        , "formset1": formset1
        , "formset2": formset2
        , "instance": platillo
        , "error": err
    }

    if request.method == "POST":
        form = PlatilloForm(request.POST, instance=platillo)
        formset1 = PlatilloIngFormset(request.POST, instance=platillo)
        formset2 = PlatilloRecFormset(request.POST, instance=platillo)

        if form.is_valid() and formset1.is_valid() and formset2.is_valid:
            if 'bebida' in request.resolver_match.view_name:
                form.cleaned_data['bebida'] = True
            else:
                form.cleaned_data['bebida'] = False
            client_mod = form.save()
            id = client_mod.id
            formset1.save()
            formset2.save()

            if 'bebida' in request.resolver_match.view_name:
                # TODO redirect to platillo view
                return redirect('menu:bebidas')
            return redirect('menu:platillos')
        else:
            if 'bebida' in request.resolver_match:
                url = "/menu/bebidas/cambiar/%(id)s/?err=warning" % {"id": pk}
            else:
                url = "/menu/platillos/cambiar/%(id)s/?err=warning" % {"id": pk}
            return HttpResponseRedirect(url)

    if 'bebida' in request.resolver_match.view_name:
        url = 'menu/bebida_edit_form.html'
    else:
        url = 'menu/platillo_edit_form.html'
    return render(request, url, dict)


def proveedor_modifier(request, pk):
    proveedor = Proveedor.objects.get(id=pk)
    form = ProveedorForm(instance=proveedor)

    dict = {
        "form": form
        , "instance": proveedor
    }

    if request.method == "POST":
        form = ProveedorForm(request.POST, instance=proveedor)

        if form.is_valid():
            client_mod = form.save()
            id = client_mod.id
            return redirect('menu:proveedores')

    dict['form'] = form
    return render(request, 'menu/proveedor_edit.html', dict)


class IngredienteUpdateView(UpdateView):
    model = Ingrediente
    form_class = IngredienteForm
    template_name = 'menu/ingrediente_edit.html'

    def dispatch(self, *args, **kwargs):
        self.item_id = kwargs['pk']
        return super(IngredienteUpdateView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        form.save()
        item = Ingrediente.objects.get(id=self.item_id)
        # TODO view edited item
        return redirect("menu:ingredientes")


class ProveedorUpdateView(UpdateView):
    model = Proveedor
    form_class = ProveedorForm
    template_name = 'menu/proveedor_edit.html'

    def dispatch(self, *args, **kwargs):
        self.item_id = kwargs['pk']
        return super(ProveedorUpdateView, self).dispatch(*args, **kwargs)


def analisis(request):
    tipo = request.GET['tipo'] if 'tipo' in request.GET else 'platillo'
    sort_by = request.GET['sort_by'] if 'sort_by' in request.GET else 'ganancia'

    dishes = Platillo.objects.filter(restaurante__id=request.user.restaurante.id)

    if tipo == 'platillo':
        dishes = dishes.filter(bebida=False)
    else:
        dishes = dishes.filter(bebida=True)

    if 'min-price' in request.GET and request.GET['min-price'] != '':
        dishes = dishes.filter(precio__gt=float(request.GET['min-price']))
    if 'max-price' in request.GET and request.GET['max-price'] != '':
        dishes = dishes.filter(precio__lt=float(request.GET['max-price']))
    if sort_by == 'ganancia':
        good_dishes = dishes.order_by('-ganancia')
        bad_dishes = dishes.order_by('ganancia')
    else:
        good_dishes = dishes.order_by('costo_percentaje')
        bad_dishes = dishes.order_by('-costo_percentaje')
    context = {
        'tipo': tipo,
        'sort_by': sort_by,
        'platillosgood': good_dishes[:5],
        'platillosbad': bad_dishes[:5],
    }
    return render(request, 'menu/analisis.html', context)


def proveedores(request, error=None):
    if request.method == "POST":
        form = ProveedorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('menu:proveedores')
        return render(request, 'menu/proveedores.html', {'form': form})
    else:
        prov = Proveedor.objects.filter(restaurante__id=request.user.restaurante.id)
        context = {
            'proveedores': prov,
            'form': ProveedorForm(),
            'error':  error,
        }
        return render(request, 'menu/proveedores.html', context)


def proveedores_delete_error(request):
    return proveedores(request, 'error')


def del_proveedores(request, pk):
    try:
        Proveedor.objects.get(pk=pk).delete()
    except ProtectedError:
        return redirect('menu:proveedores_error')
    return redirect('menu:proveedores')


def platillos(request):
    if request.method == "POST":
        return create_platillo(request)
    else:
        rest = request.user.restaurante
        plats = Platillo.objects.filter(restaurante__id=rest.id, bebida=False)
        context = {
            'restaurante': rest,
            'platillos': plats,
            'ingredientes': Ingrediente.objects.filter(restaurante__id=rest.id),
            'recetas': Receta.objects.filter(restaurante__id=rest.id),
            'tipo': 'platillo',
            'form': PlatilloForm(),
        }
        return render(request, 'menu/platillos.html', context)


def create_platillo(request):
    mi_ingredientes = Ingrediente.objects.filter(
        pk__in=request.POST.getlist('added-ing[]'))
    mi_recetas = Receta.objects.filter(
        pk__in=request.POST.getlist('added-rec[]'))
    fields = {
        'restaurante': request.user.restaurante,
        'nombre': request.POST['nombre'],
        'precio': request.POST['precio'],
        'bebida': 'bebidas' in request.resolver_match.view_name,
        'costo': 0  # temp for first save
    }
    cost = 0
    platillo = Platillo.objects.create(**fields)
    for ing in mi_ingredientes:
        q = float(request.POST['ing-' + str(ing.id)])
        ing_fields = {
            'platillo': platillo,
            'ingrediente': ing,
            'cantidad': q
        }
        cost += ing.unit_cost * q
        PlatilloIng.objects.create(**ing_fields)
    for rec in mi_recetas:
        q = float(request.POST['rec-' + str(rec.id)])
        rec_fields = {
            'platillo': platillo,
            'receta': rec,
            'cantidad': q
        }
        cost += rec.unit_cost * q
        PlatilloRec.objects.create(**rec_fields)
    platillo.costo = cost
    platillo.save()
    if 'bebidas' in request.resolver_match.view_name:
        redirect_to = 'menu:bebidas'
    else:
        redirect_to = 'menu:platillos'
    return redirect(redirect_to)


def del_platillo(request):
    for _id in request.POST.getlist('plat-del[]'):
        Platillo.objects.get(id=_id).delete()
    return redirect('menu:bebidas' if 'bebidas' in request.resolver_match.view_name else 'menu:platillos')


def bebidas(request):
    if request.method == "POST":
        return create_platillo(request)
    else:
        rest = request.user.restaurante
        plats = Platillo.objects.filter(restaurante__id=rest.id, bebida=True)
        context = {
            'restaurante': rest,
            'platillos': plats,
            'ingredientes': Ingrediente.objects.filter(restaurante__id=rest.id),
            'recetas': Receta.objects.filter(restaurante__id=rest.id),
            'tipo': 'bebida',
            'form': PlatilloForm(),
        }
        return render(request, 'menu/platillos.html', context)


def ingredientes(request):
    if request.method == "POST":
        fields = {
            'restaurante': request.user.restaurante,

templates/menu/bebidas.html
{% extends "base.html" %}
{% block title %}Bebidas{% endblock %}
{% block content %}
{% include "menu/menu_tabs.html" %}
{% endblock %}

templates/menu/ingredientes.html
{% extends "base.html" %}{% load myfilters %}
{% block title %}Ingredientes{% endblock %}
{% block content %}
{% include "menu/menu_tabs.html" %}
<div class="modal" id="add-ing" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">A&ntilde;adir Ingrediente</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="POST" action="{% url 'menu:ingredientes' %}">
      {% csrf_token %}
      <div class="modal-body">
      {% load myfilters %}
      <div class="form-row">
          <div class="col-6 form-group">
             {{ form.nombre.label_tag }}
             {{ form.nombre|addclass:'form-control' }}
          </div>
          <div class="col-6 form-group">
             {{ form.marca.label_tag }}
             {{ form.marca|addclass:'form-control' }}
          </div>
      </div>
      <div class="form-row">
      <div class="form-group col-3">
        <label for="input-proveedor">Proveedor:</label>

      </div>
      <div class="form-group col-9">
         <select id="input-proveedor" class="form-control" name="input-proveedor">
              {% for proveedor in proveedores %}
              <option value="{{ proveedor.id }}">{{ proveedor.nombre }}</option>
              {% endfor %}
          </select>
      </div>
      </div>
      <div class="form-row">
          <div class="form-group col-6">
             {{ form.cantidad.label_tag }}
             {{ form.cantidad|addclass:'form-control' }}
          </div>
        <div class="form-group col-6" style="margin-top: 0;">
          {{ form.medida|addclass:'form-control' }}
        </div>
      </div>
      <div class="form-group">
         {{ form.costo.label_tag }}
         {{ form.costo|addclass:'form-control' }}
      </div>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">A&ntilde;adir</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
      </form>
    </div>
  </div>
</div>
<div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title ">Ingredientes</h4>
        </div>
    <div class="card-body">
    <form method="POST" action="{% url 'menu:ingredientes_delete' %}">
    {% csrf_token %}
    {% if ingredientes.count > 0 %}
    <button class="btn btn-danger"><i class="material-icons">delete</i></button>
    <a class="btn btn-info" type="button" href="{% url 'menu:export' %}"><i class="material-icons">get_app</i></a>
    {% endif %}
    <button class="btn btn-primary" type="button" data-toggle="modal" data-target="#add-ing"><i class="material-icons">add</i></button>
    {% if error != None %}
        <div class="alert alert-warning" role="alert">
        {{ error }}
        </div>
    {% endif %}
        {% if ingredientes.count > 0 %}
    <div class="table-responsive">
        <table class="table table-striped">
            <thead class="text-primary">
                <tr>
                    <th></th>
                    <th>Nombre</th>
                    <th>Marca</th>
                    <th>Proveedor</th>
                    <th>Costo</th>
                    <th class="text-right">Acci&oacute;n</th>
                </tr>
            </thead>
            <tbody>
            {#TODO make table more narrow, expand to modal for more information#}
            {#TODO collapsable table columns#}
            {% for ingredient in ingredientes %}
                <tr>
                <td>
                    <div class="form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" type="checkbox" name="ing-del[]" value="{{ ingredient.id }}" >
                            <span class="form-check-sign">
                                <span class="check"></span>
                            </span>
                        </label>
                    </div>
                </td>
                <td>{{ ingredient.nombre }}</td>
                <td>{{ ingredient.marca }}</td>
                <td>{{ ingredient.proveedor }}</td>
                <td>{{ ingredient.unit_cost|currency }}/{{ ingredient.medida }}</td>
                <td class="td-actions text-right">
                    <a rel="tooltip" class="btn btn-success ing-edit" href="{% url 'menu:ingredientes_edit' ingredient.pk %}">
                        <i class="material-icons">edit</i>
                    </a>
                </td></tr>
            {% endfor %}
            </tbody>
            </table>
        </div>
    {% endif %}
    </form>
    </div>
  </div>
</div>
</div>
{% endblock %}

templates/menu/proveedor_edit.html
{% extends 'base.html' %}
{% block content %}
{% include 'menu/menu_tabs.html' %}
    <div class="card">
    <div class="card-header card-header-primary">
        <h4>Cambiar Proveedor</h4>
    </div>
    <form method="POST" action="{% url 'menu:proveedores_edit' instance.pk %}">
        {% csrf_token %}
    <div class="card-body">{% load myfilters %}
        <div class="form-row">
            <div class="form-group col-6">
                {{ form.nombre.label_tag }}{{ form.nombre|addclass:'form-control' }}
            </div>
            <div class="form-group col-6">
                {{ form.telefono.label_tag }}{{ form.telefono|addclass:'form-control' }}
                {% for error in form.telefono.errors %}
                    <li><span class="fa fa-exclamation-triangle"></span> <strong>{{ error|escape }}</strong></li>
                {% endfor %}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-6">
                {{ form.representante.label_tag }}{{ form.representante|addclass:'form-control' }}
            </div>
            <div class="form-group col-6">
                {{ form.telefono_de_representante.label_tag }}{{ form.telefono_de_representante|addclass:'form-control' }}
                {% for error in form.telefono_de_representante.errors %}
                    <div class="alert alert-warning"><strong>{{ error|escape }}</strong></div>
                {% endfor %}
            </div>
        </div>
        <div class="form-group">
            {{ form.correo_electronico.label_tag }}{{ form.correo_electronico|addclass:'form-control' }}
        </div>
    </div>
    <div class="card-footer">
        <a class="btn btn-default" href="{% url 'menu:proveedores' %}"><i class="material-icons">keyboard_return</i></a>
        <button type="submit" class="btn btn-primary" value="Update"><i class="material-icons">check</i></button>
    </div>
    </form>
    </div>
{% endblock %}

templates/menu/proveedores.html
{% extends "base.html" %}
{% block title %}Proveedores{% endblock %}
{% block content %}
{% include "menu/menu_tabs.html" %}
<div class="modal" id="add-prov" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">A&ntilde;adir Proveedor</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="POST" action="{% url 'menu:proveedores' %}">
      {% csrf_token %}
      <div class="modal-body">
          {% load myfilters %}
      <div class="form-row">
          <div class="col-6 form-group">
              {{ form.nombre.label_tag }}
             {{ form.nombre|addclass:'form-control' }}
          </div>
          <div class="col-6 form-group">
              {{ form.telefono.label_tag }}
              {{ form.telefono|addclass:'form-control' }}
          </div>
      </div>
      <div class="form-row">
          <div class="col-6 form-group">
              {{ form.representante.label_tag }}
              {{ form.representante|addclass:'form-control' }}
          </div>
          <div class="col-6 form-group">
              {{ form.telefono_de_representante.label_tag }}
              {{ form.telefono_de_representante|addclass:'form-control' }}
          </div>
      </div>
      <div class="form-group">
          {{ form.correo_electronico.label_tag }}
          {{ form.correo_electronico|addclass:'form-control' }}
      </div>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">A&ntilde;adir</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
      </form>
    </div>
  </div>
</div>

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#add-prov"><i class="material-icons">add</i></button>
{% if proveedores.count > 0 %}
    {# TODO split into two columns #}
    {% for proveedor in proveedores %}
    {% if forloop.first %}<div class="row">{% endif %}
    <div class="col-md-4">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">{{ proveedor.nombre }}</h4>
            <h6 class="card-subtitle mb-2 text-muted">{{ proveedor.correo_electronico }}</h6>
            <p class="card-text">
                Tel&eacute;fono: {{ proveedor.telefono }}<br/>
                Representante: {{ proveedor.representante }}<br/>
                Tel&eacute;fono de Rep: {{ proveedor.telefono_de_representante }}
            </p>
        </div>
        <div class="card-footer">
            <a rel="tooltip" class="btn" href="{% url 'menu:proveedores_delete' proveedor.pk %}"><i class="material-icons">delete</i></a>
            <a class="btn" href="{% url 'menu:proveedores_edit' proveedor.pk %}"><i class="material-icons">edit</i></a>
        </div>
    </div>
    </div>
    {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
    {% if forloop.last %}</div>{% endif %}
{% endfor %}
{% endif %}
{% endblock %}

templates/menu/recetas.html
{% extends "base.html" %}
{% block title %}Recetas{% endblock %}
{% block content %}
{% include "menu/menu_tabs.html" %}
<div class="modal" id="add-prov" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">A&ntilde;adir Receta</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="POST" action="{% url 'menu:recetas' %}">
      {% csrf_token %}{% load myfilters %}
      <div class="modal-body">
      <div class="form-group">
          {{ form.nombre.label_tag }}
          {{ form.nombre|addclass:'form-control' }}
      </div>
      <div class="form-row">
          <div class="form-group col-6">
          {{ form.cantidad.label_tag }}
          {{ form.cantidad|addclass:'form-control' }}
          </div>
        <div class="form-group col-6" style="margin-top: 0;">
          {{ form.medida|addclass:'form-control' }}
        </div>
      </div>
      <div class="form-group">
       <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text">
              <i class="material-icons">search</i>
          </span>
        </div>
        <input type="text" class="form-control" id="add-receta-filter" placeholder="Filtrar ingredientes">
      </div>

        {# TODO add button for ingredientes #}
      </div>
      <div class="table-responsive table-wrapper-scroll-y">
          <table class="table table-condensed table-filter" id="add-receta-table">
              <thead>
                <tr class="table-head">
                    <th>Usado</th>
                    <th>Ingrediente</th>
                    <th>Costo</th>
                    <th>Cantidad</th>
                    <th>Medida</th>
                </tr>
                </thead>
                <tbody>
                {% for ingredient in ingredientes %}
                    <tr>
                        <td>
                          <div class="form-check">
                              <label class="form-check-label">
                                  {# TODO checkbox enables quantity field #}
                                  <input class="form-check-input" type="checkbox" name="added-ing[]" value="{{ ingredient.id }}" >
                                  <span class="form-check-sign">
                                      <span class="check"></span>
                                  </span>
                              </label>
                          </div>
                        </td>
                        <td>{{ ingredient.nombre }}</td>
                        <td>{{ ingredient.unit_cost|currency }}/{{ ingredient.medida }}</td>
                        <td><input type="number" class="form-control" name="ing-{{ ingredient.id }}"></td>
                        <td>{{ ingredient.medida }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">A&ntilde;adir</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
      </div>
      </form>
    </div>
  </div>
</div>
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
</div><!-- /.modal -->
<div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title ">Recetas</h4>
        </div>
    <div class="card-body">
    <form method="POST" action="{% url 'menu:recetas_delete' %}">
    {% csrf_token %}
    {% if recetas.count > 0 %}
    <button class="btn btn-danger" type="submit"><i class="material-icons">delete</i></button>
    <a class="btn btn-info" href="{% url 'menu:export' %}"><i class="material-icons">get_app</i></a>
    {% endif %}
    <button class="btn btn-primary" type="button" data-toggle="modal" data-target="#add-prov"><i class="material-icons">add</i></button>
    {% if error != None %}
    <div class="alert alert-warning" role="alert">
    {{ error }}
    </div>
    {% endif %}
    {% if recetas.count > 0 %}
        <div class="table-responsive">
        <table class="table table-striped">
            <thead class="text-primary">
                <tr>
                    <th></th>
                    <th>Nombre</th>
                    <th>Costo</th>
                    <th class="text-right">Acci&oacute;n</th>
                </tr>
            </thead>
            <tbody>
            {#TODO make table more narrow, expand to modal for more information#}
            {#TODO collapsable table coluemns#}
            {% for receta in recetas %}
                <tr>
                <td>
                      <div class="form-check">
                          <label class="form-check-label">
                              {# TODO checkbox enables quantity field #}
                              <input class="form-check-input" type="checkbox" name="rec-del[]" value="{{ receta.id }}" >
                              <span class="form-check-sign">
                                  <span class="check"></span>
                              </span>
                          </label>
                      </div>
                </td>
                <td>{{ receta.nombre }}</td>
                <td>{{ receta.unit_cost|currency }}/{{ receta.medida }}</td>
                <td class="td-actions text-right">
                    <a rel="tooltip" class="btn btn-success" href="{% url 'menu:recetas_edit' receta.pk %}" >
                        <i class="material-icons">edit</i>
                    </a>
                </td></tr>
            {% endfor %}
            </tbody>
            </table>
        </div>
    {% endif %}
    </form>
    </div>
  </div>
</div>
</div>
{% endblock %}